### ISSUE TITLE
V2: FMCTLU producer: No eudaq warning or error when clockfile path wrong

### ISSUE THREAD

**Issue by arummler** [eudaq/eudaq#452]
There is an error message on cout but not propagated to eudaq. Makes it easy to miss.

**Comment by PaoloGB** [comment]
This should now be fixed with merge 900d9207020e141194a91e6a99f229b7dbc2e46e.
If the specified clock file is missing, the producer will throw an EUDAQ log error.

In the scenario where the steering card _CLOCK_CFG_FILE_ is missing in the INI file, the producer will throw an EUDAQ warning. This is because in that case the system uses the default clock configuration file shipped with EUDAQ.

I tested both scenarios and had no issue on our local setup so I think it is safe to close this, unless further features are required.
