### ISSUE TITLE
EUDAQ2: dynamic exception error (error: ISO C++17 does not allow dynamic exception specifications) 

### ISSUE THREAD

**Issue by ajitkmaurya** [eudaq/eudaq#703]
Hello,

I am trying to compile eudaq2 with `-DEUDAQ_LIBRARY_BUILD_LCIO=ON`. But it gives me following error.

`/eudaq2/extern/include/EVENT/LCEvent.h:66:74: error: ISO C++17 does not allow dynamic exception specifications`
`66 |     virtual LCCollection * getCollection(const std::string & name) const throw (DataNotAvailableException, std::exception )  = 0;`

Could you please suggest how to solve this.

EUDAQ2 version: 2.5.2
OS: Ubuntu 22.04

Thanks 
Ajit

**Comment by simonspa** [comment]
The issue is that (for some reason) EUDAQ bundles a very outdated zipped version of the LCIO library here: https://github.com/eudaq/eudaq/tree/master/main/lib/lcio/extern
This should definitely be removed @lhuth @herkerta 

But in the meantime, you can do the following:

* get a recent copy of LCIO (from here: )
* Compile it with
   ```
   mkdir build && cd build/
   cmake -DCMAKE_INSTALL_PREFIX=/path/to/your/eudaq/extern/ ..
   make install -j
   ```
* Then recompile EUDAQ with clean build directory and it should find your externally built library.

**Comment by ajitkmaurya** [comment]
Thank you! 
It works.

**Comment by simonspa** [comment]
Please don't close, this is just a workaround
